# src/otel-collector/otelcol-config-extras.yml
exporters:
  otlphttp/my_backend:
    endpoint: localhost:4317
    headers:
      # Authorization: "Bearer YOUR_API_KEY"
      # or, depending on the vendor:
      api-key: "3be1a4ad103cf21a7f6c9234b94a3ce150274a818c5167373baf98caa678d2e7"
      # x-honeycomb-team: "YOUR_API_KEY"

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlphttp/my_backend]
    metrics:
      exporters: [otlphttp/my_backend]
    logs:
      exporters: [otlphttp/my_backend]